export const ProfileActionsConstants = {
    FETCH_PROFILE_REQUEST: 'FETCH_PROFILE_REQUEST',
    FETCH_PROFILE_FAILURE: 'FETCH_PROFILE_FAILURE',
    FETCH_PROFILE_SUCCESS: 'FETCH_PROFILE_SUCCESS',
    UPDATE_PROFILE_REQUEST: 'UPDATE_PROFILE_REQUEST',
    UPDATE_PROFILE_FAILURE: 'UPDATE_PROFILE_FAILURE',
    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
    CLEAR_PROFILE: 'CLEAR_PROFILE'
};
