export const RestaurantsActions = {
    FETCH_ALL_RESTAURANTS: "FETCH_ALL_RESTAURANTS",
    FETCH_ALL_RESTAURANTS_RESULT: "FETCH_ALL_RESTAURANTS_RESULT",

    ADD_REVIEW: "ADD_REVIEW",
    ADD_REVIEW_RESULT: "ADD_REVIEW_RESULT",

    GET_RESTAURANT_REVIEWS: 'GET_RESTAURANT_REVIEWS',
    GET_RESTAURANT_REVIEWS_RESULT: 'GET_RESTAURANT_REVIEWS_RESULT'
};
