export const RestaurantsActions = {
    FETCH_ALL_RESTAURANTS: "FETCH_ALL_RESTAURANTS",
    FETCH_ALL_RESTAURANTS_RESULT: "FETCH_ALL_RESTAURANTS_RESULT",

    ADD_REVIEW: "ADD_REVIEW",
    ADD_REVIEW_RESULT: "ADD_REVIEW_RESULT",

    ADD_RESTAURANT: "ADD_RESTAURANT",
    ADD_RESTAURANT_RESULT: "ADD_RESTAURANT_RESULT",

    SEARCH_RESTAURANT: "SEARCH_RESTAURANT",
    SEARCH_RESTAURANT_SUCCESS: "SEARCH_RESTAURANT_SUCCESS",
    SEARCH_RESTAURANT_FAILURE: "SEARCH_RESTAURANT_FAILURE"
};
