export const RegistrationActionsConstants = {
    VALIDATE_USERNAME_UNIQUE: 'VALIDATE_USERNAME_UNIQUE',
    VALIDATE_USERNAME_UNIQUE_SUCCESS: 'VALIDATE_USERNAME_UNIQUE_SUCCESS',
    VALIDATE_USERNAME_UNIQUE_FAILURE: 'VALIDATE_USERNAME_UNIQUE_FAILURE',
    LOCATION_CHANGED: 'LOCATION_CHANGED',
    REGISTER_USER: 'REGISTER_USER',
    REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE'
};
