export const RegistrationActionsConstants = {
    SET_USERNAME: 'SET_USERNAME',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_REQUEST_FAILURE: 'LOGIN_REQUEST_FAILURE',
    VALIDATE_USERNAME_UNIQUE: 'VALIDATE_USERNAME_UNIQUE',
    VALIDATE_USERNAME_UNIQUE_SUCCESS: 'VALIDATE_USERNAME_UNIQUE_SUCCESS',
    VALIDATE_USERNAME_UNIQUE_FAILURE: 'VALIDATE_USERNAME_UNIQUE_FAILURE',
    REGISTER_USER: 'REGISTER_USER',
    REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',
    CLEAR_ERROR: 'CLEAR_ERROR'
};
